### PR TITLE
Downgrade the minimum version of Java from 16 to 8.

### PR DESCRIPTION
**Pull request by 0rangeFox**
Hey 👋, I created this PR with the aim of adding compatibility with lower versions, I think it makes sense and it should be supported at least to 8 because it is still used by many platforms and applications.

I've done my best to convert it, I've tested it and so far everything is working, but if you have any errors, just let me know and I'll be happy to help.

That's all for now, and I'd also like to thank you for the foundation of this library for Java.

### CODE REVIEW

**Comment by isaackogan** [comment]
Man I think I'd cry if TikTokLive python had to support Python 2

**Comment by 0rangeFox** [comment]
> Man I think I'd cry if TikTokLive python had to support Python 2

Ahahah, but honestly, you escaped that because nowadays Python 2 is no longer used, if it is still being used, you have to tell them to upgrade.

**Comment by jwdeveloper** [comment]
I really appriciate time you spend working on this PR, however using Java 16 was conscious decision and I will stick to this version

**Comment by 0rangeFox** [comment]
You're welcome, I appreciate you doing the hard part. So I see that the license is [MIT](https://github.com/jwdeveloper/TikTokLiveJava?tab=MIT-1-ov-file#readme), can I take this fork and _upstream_ its changes and always maintain compatibility with Java 8 and thus publish it on the maven portal _(On my behalf)_ so that other folks who are interested can also integrate it in a lower version of Java?

**Pull request closed without merging**
